/**
 * Global constants and configuration
 */

// Detect language from game settings
const isZHInGameSetting = localStorage.getItem("i18nextLng")?.toLowerCase()?.startsWith("zh");
let isZH = isZHInGameSetting;

// Default settings structure
let settingsMap = {
    customAvatar: {
        id: "customAvatar",
        desc: isZH ? "启用自定义头像" : "Enable custom avatar",
        isTrue: false,
        avatarUrl: "",
    },
    spritesheetAvatar: {
        id: "spritesheetAvatar",
        desc: isZH ? "启用精灵动画头像" : "Enable spritesheet avatar animations",
        enabled: false,
        idleUrl: "",
        castUrl: "",
        idleFrames: 6,
        castFrames: 8,
        frameWidth: 231,
        frameHeight: 190,
        idleDuration: 600,
        castDuration: 800,
    },
    myCharacterColor: {
        id: "myCharacterColor",
        desc: isZH ? "使用固定角色颜色" : "Use Persistent Character Color",
        isTrue: false,
        r: 147,
        g: 51,
        b: 234,
        frameR: 147,
        frameG: 51,
        frameB: 234,
    },
    tracker0 : {
        id: "tracker0",
        desc: isZH ? "启用玩家 #1 伤害线":"Enable player #1 damage line",
        isTrue: true,
        descH: isZH ? "启用玩家 #1 治疗线":"Enable player #1 healing line",
        isTrueH: true,
        r: 255,
        g: 99,
        b: 132,
        frameR: 255,
        frameG: 99,
        frameB: 132,
        detectionMode: "manual",
        attackAnimation: "none",
        fireballColor: "green",
    },
    tracker1 : {
        id: "tracker1",
        desc: isZH ? "启用玩家 #2 伤害线":"Enable player #2 damage line",
        isTrue: true,
        descH: isZH ? "启用玩家 #2 治疗线":"Enable player #2 healing line",
        isTrueH: true,
        r: 54,
        g: 162,
        b: 235,
        frameR: 54,
        frameG: 162,
        frameB: 235,
        detectionMode: "manual",
        attackAnimation: "none",
        fireballColor: "green",
    },
    tracker2 : {
        id: "tracker2",
        desc: isZH ? "启用玩家 #3 伤害线":"Enable player #3 damage line",
        isTrue: true,
        descH: isZH ? "启用玩家 #3 治疗线":"Enable player #3 healing line",
        isTrueH: true,
        r: 255,
        g: 206,
        b: 86,
        frameR: 255,
        frameG: 206,
        frameB: 86,
        detectionMode: "manual",
        attackAnimation: "none",
        fireballColor: "green",
    },
    tracker3 : {
        id: "tracker3",
        desc: isZH ? "启用玩家 #4 伤害线":"Enable player #4 damage line",
        isTrue: true,
        descH: isZH ? "启用玩家 #4 治疗线":"Enable player #4 healing line",
        isTrueH: true,
        r: 75,
        g: 192,
        b: 192,
        frameR: 75,
        frameG: 192,
        frameB: 192,
        detectionMode: "manual",
        attackAnimation: "none",
        fireballColor: "green",
    },
    tracker4 : {
        id: "tracker4",
        desc: isZH ? "启用玩家 #5 伤害线":"Enable player #5 damage line",
        isTrue: true,
        descH: isZH ? "启用玩家 #5 治疗线":"Enable player #5 healing line",
        isTrueH: true,
        r: 153,
        g: 102,
        b: 255,
        frameR: 153,
        frameG: 102,
        frameB: 255,
        detectionMode: "manual",
        attackAnimation: "none",
        fireballColor: "green",
    },
    tracker6 : {
        id: "tracker6",
        desc: isZH ? "启用敌人伤害线":"Enable enemies damage line",
        isTrue: true,
        descH: isZH ? "启用敌人治疗线":"Enable enemies healing line",
        isTrueH: true,
        r: 255,
        g: 0,
        b: 0,
        frameR: 255,
        frameG: 0,
        frameB: 0,
    },
    missedLine : {
        id: "missedLine",
        desc: isZH ? "启用被闪避的攻击线":"Enable missed attack line",
        isTrue: true,
    },
    moreEffect : {
        id: "moreEffect",
        desc: isZH ? "特效拓展：击中时有粒子效果和目标震动":"Effects extension: particle effects & Target shake on hit",
        isTrue: true,
    },
    keepOriginalDamageColor : {
        id: "keepOriginalDamageColor",
        desc: isZH ? "显示原始伤害颜色（动画结束后恢复红色）" : "Show original damage color (return to red after animation)",
        isTrue: true,
    }
};

// Export to global scope for Tampermonkey
window.isZH = isZH;
window.settingsMap = settingsMap;
